services:
  kupuri-landing:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kupuri-landing
    restart: unless-stopped
    networks:
      - coolify
    labels:
      - traefik.enable=true

      # HTTP -> HTTPS redirect
      - traefik.http.middlewares.kupuri-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.kupuri-landing-http.rule=Host(`kupuri.31.220.58.212.sslip.io`)
      - traefik.http.routers.kupuri-landing-http.entrypoints=http
      - traefik.http.routers.kupuri-landing-http.middlewares=kupuri-https-redirect

      # HTTPS site
      - traefik.http.routers.kupuri-landing-https.rule=Host(`kupuri.31.220.58.212.sslip.io`)
      - traefik.http.routers.kupuri-landing-https.entrypoints=https
      - traefik.http.routers.kupuri-landing-https.tls=true
      - traefik.http.routers.kupuri-landing-https.tls.certresolver=letsencrypt
      - traefik.http.routers.kupuri-landing-https.service=kupuri-landing
      - traefik.http.services.kupuri-landing.loadbalancer.server.port=3000

networks:
  coolify:
    external: true
