services:
  :
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 
    restart: unless-stopped
    networks:
      - coolify
    labels:
      - traefik.enable=true
      - traefik.http.routers..rule=Host(\${HOSTNAME}\\)
      - traefik.http.routers..entrypoints=websecure
      - traefik.http.routers..tls=true
      - traefik.http.routers..tls.certresolver=letsencrypt
      - traefik.http.services..loadbalancer.server.port=3000

networks:
  coolify:
    external: true
